apiVersion: v1
kind: Service
metadata:
  name: dbinventory
spec:
  selector:
    app: dbinventory
  ports:
    - protocol: "TCP"
      port: 5433
      targetPort: 5432
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbinventory
spec:
  selector:
    matchLabels:
      app: dbinventory
  replicas: 1
  template:
    metadata:
      labels:
        app: dbinventory
    spec:
      containers:
        - name: dbinventory
          image: postgres:14.1
          env:
            - name: POSTGRES_DB
              value: "inventory"
            - name: POSTGRES_USER
              value: "inventory"
            - name: POSTGRES_PASSWORD
              value: "inventory"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432