apiVersion: v1
kind: Service
metadata:
  name: dblaboratory
spec:
  selector:
    app: dblaboratory
  ports:
    - protocol: "TCP"
      port: 5432
      targetPort: 5432
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dblaboratory
spec:
  selector:
    matchLabels:
      app: dblaboratory
  replicas: 1
  template:
    metadata:
      labels:
        app: dblaboratory
    spec:
      containers:
        - name: dblaboratory
          image: postgres:14.1
          env:
            - name: POSTGRES_DB
              value: "laboratory"
            - name: POSTGRES_USER
              value: "laboratory"
            - name: POSTGRES_PASSWORD
              value: "laboratory"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432