eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: tenant-service
server:
  port: 7070

logging:
  level:
    org:
      springframework:
        web: debug
redis:
  host: localhost
  port: 6379
