eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: tenant-service

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      expose: prometheus
      exposure:
        include: "*"

server:
  port: 7070

logging:
  level:
    org:
      springframework:
        web: debug
redis:
  host: localhost
  port: 6379
