spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_NLvOVvUVE

server:
  port: 9090

logging:
  level:
    org:
      springframework:
        web: debug
