eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_NLvOVvUVE

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      expose: prometheus
      exposure:
        include: "*"
server:
  port: 9090

logging:
  level:
    org:
      springframework:
        web: debug
