spring:
  application:
    name: discovery
server:
  port: 8761

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      expose: prometheus
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: false

logging:
  level:
    org:
      springframework:
        web: debug
